name: mittens CD

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.19.2'
      - run: flutter pub get
      - run: flutter build web
      - uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: ./build/web/
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: ./build/web/
      - name: copy file to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: ./build/web/*
          target: /home/rizal/mittens/mittens
      - name: Change cfg file
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cp ~/mittens/envs/cfg.yaml ~/mittens/mittens/build/web/assets/assets/cfg
            sudo cp -R ~/mittens/mittens/build/web/* /var/www/html
            sudo rm -R  ~/mittens/mittens/*
